### ISSUE TITLE
win10 系统上正常加载了libopencv_java455.dll 但是 new WeChatQRCode（）org.opencv.wechat_qrcode.WeChatQRCode.WeChatQRCode_4()J 

### ISSUE THREAD

**Issue by zk020106** [jenly1314/WeChatQRCode#38]
八月 16, 2023 2:05:51 下午 com.zk.qrcode.OpenCV initOpenCV
信息: os.name = windows 10
八月 16, 2023 2:05:51 下午 com.zk.qrcode.OpenCV initOpenCV
信息: Successfully loaded OpenCV native library.
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.opencv.wechat_qrcode.WeChatQRCode.WeChatQRCode_4()J
	at org.opencv.wechat_qrcode.WeChatQRCode.WeChatQRCode_4(Native Method)
	at org.opencv.wechat_qrcode.WeChatQRCode.<init>(WeChatQRCode.java:90)
	at com.zk.qrcode.WeChatQRCodeDetector.initWeChatQRCode(WeChatQRCodeDetector.java:55)
	at com.zk.qrcode.WeChatQRCodeDetector.init(WeChatQRCodeDetector.java:37)
	at com.zk.qrcode.WeChatQRCodeDetector.init(WeChatQRCodeDetector.java:27)
	at com.zk.qrcode.QrcodeDemo.main(QrcodeDemo.java:12)

Process finished with exit code 1

**Comment by EVANGELION-K** [comment]
同问

**Comment by WangRui1416431931** [comment]
解决了嘛？

**Comment by redhatqiang** [comment]
这个问题还是没解决  在二群也提问了
