### ISSUE TITLE
demo闪退 No implementation found for long org.opencv.wechat_qrcode.WeChatQRCode.WeChatQRCode_0(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (tried Java_org_opencv_wechat_1qrcode_WeChatQRCode_WeChatQRCode_10 and Java_org_opencv_wechat_1qrcode_WeChatQRCode_WeChatQRCode_10__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)

### ISSUE THREAD

**Issue by SIAWET** [jenly1314/WeChatQRCode#48]
和 https://github.com/jenly1314/WeChatQRCode/issues/47 相同的报错 但我是将Release2.1.0下载下来后在Android Studio 中编译安装的，demo一打开就闪退 
电脑 win10
手机 vivo iQOO NEO 855版 安卓11

**Comment by SIAWET** [comment]
---------------------------- PROCESS STARTED (10670) for package com.king.wechat.qrcode.app ----------------------------
2024-02-29 18:41:00.443 chat.qrcode.app                      W  type=1400 audit(0.0:282122): avc: denied { search } for name="bbkcore" dev="sda19" ino=3702 scontext=u:r:untrusted_app:s0:c129,c259,c512,c768 tcontext=u:object_r:vivo_data_file:s0 tclass=dir permissive=0 app=com.king.wechat.qrcode.app
2024-02-29 18:41:00.443 chat.qrcode.app                      W  type=1400 audit(0.0:282124): avc: denied { search } for name="bbkcore" dev="sda19" ino=3702 scontext=u:r:untrusted_app:s0:c129,c259,c512,c768 tcontext=u:object_r:vivo_data_file:s0 tclass=dir permissive=0 app=com.king.wechat.qrcode.app
2024-02-29 18:41:00.443 chat.qrcode.app                      W  type=1400 audit(0.0:282125): avc: denied { search } for name="bbkcore" dev="sda19" ino=3702 scontext=u:r:untrusted_app:s0:c129,c259,c512,c768 tcontext=u:object_r:vivo_data_file:s0 tclass=dir permissive=0 app=com.king.wechat.qrcode.app
2024-02-29 18:41:00.630 NetworkSecurityConfig                D  No Network Security Config specified, using platform default
2024-02-29 18:41:00.630 NetworkSecurityConfig                D  No Network Security Config specified, using platform default
2024-02-29 18:41:00.718 chat.qrcode.ap                       W  Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2024-02-29 18:41:00.719 chat.qrcode.ap                       W  Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2024-02-29 18:41:00.769 OpenCV/StaticHelper                  D  First attempt to load libs
2024-02-29 18:41:00.769 OpenCV/StaticHelper                  D  Trying to load library opencv_java4
2024-02-29 18:41:00.770 OpenCV/StaticHelper                  D  Cannot load library "opencv_java4"
2024-02-29 18:41:00.770 System.err                           W  java.lang.UnsatisfiedLinkError: dlopen failed: library "libopencv_java4.so" not found
2024-02-29 18:41:00.770 System.err                           W  	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
2024-02-29 18:41:00.771 System.err                           W  	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
2024-02-29 18:41:00.771 System.err                           W  	at java.lang.System.loadLibrary(System.java:1664)
2024-02-29 18:41:00.771 System.err                           W  	at org.opencv.android.StaticHelper.loadLibrary(StaticHelper.java:44)
2024-02-29 18:41:00.771 System.err                           W  	at org.opencv.android.StaticHelper.initOpenCV(StaticHelper.java:19)
2024-02-29 18:41:00.771 System.err                           W  	at org.opencv.android.OpenCVLoader.initLocal(OpenCVLoader.java:31)
2024-02-29 18:41:00.771 System.err                           W  	at org.opencv.OpenCV.initOpenCV(OpenCV.java:25)
2024-02-29 18:41:00.771 System.err                           W  	at com.king.wechat.qrcode.app.MainActivity.onCreate(MainActivity.kt:45)
2024-02-29 18:41:00.771 System.err                           W  	at android.app.Activity.performCreate(Activity.java:8129)
2024-02-29 18:41:00.771 System.err                           W  	at android.app.Activity.performCreate(Activity.java:8113)
2024-02-29 18:41:00.771 System.err                           W  	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1359)
2024-02-29 18:41:00.771 System.err                           W  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3736)
2024-02-29 18:41:00.771 System.err                           W  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3921)
2024-02-29 18:41:00.771 System.err                           W  	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
2024-02-29 18:41:00.771 System.err                           W  	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2024-02-29 18:41:00.771 System.err                           W  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2024-02-29 18:41:00.771 System.err                           W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2328)
2024-02-29 18:41:00.771 System.err                           W  	at android.os.Handler.dispatchMessage(Handler.java:106)
2024-02-29 18:41:00.771 System.err                           W  	at android.os.Looper.loop(Looper.java:257)
2024-02-29 18:41:00.771 System.err                           W  	at android.app.ActivityThread.main(ActivityThread.java:8244)
2024-02-29 18:41:00.771 System.err                           W  	at java.lang.reflect.Method.invoke(Native Method)
2024-02-29 18:41:00.771 System.err                           W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
2024-02-29 18:41:00.771 System.err                           W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)
2024-02-29 18:41:00.771 OpenCV/StaticHelper                  D  First attempt to load libs fails
2024-02-29 18:41:00.774 chat.qrcode.ap                       E  No implementation found for long org.opencv.wechat_qrcode.WeChatQRCode.WeChatQRCode_0(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (tried Java_org_opencv_wechat_1qrcode_WeChatQRCode_WeChatQRCode_10 and Java_org_opencv_wechat_1qrcode_WeChatQRCode_WeChatQRCode_10__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)
2024-02-29 18:41:00.775 AndroidRuntime                       D  Shutting down VM
2024-02-29 18:41:00.775 AndroidRuntime                       E  FATAL EXCEPTION: main
                                                                Process: com.king.wechat.qrcode.app, PID: 10670
                                                                java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.wechat_qrcode.WeChatQRCode.WeChatQRCode_0(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (tried Java_org_opencv_wechat_1qrcode_WeChatQRCode_WeChatQRCode_10 and Java_org_opencv_wechat_1qrcode_WeChatQRCode_WeChatQRCode_10__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)
                                                                	at org.opencv.wechat_qrcode.WeChatQRCode.WeChatQRCode_0(Native Method)
                                                                	at org.opencv.wechat_qrcode.WeChatQRCode.<init>(WeChatQRCode.java:44)
                                                                	at com.king.wechat.qrcode.WeChatQRCodeDetector.initWeChatQRCode(WeChatQRCodeDetector.java:87)
                                                                	at com.king.wechat.qrcode.WeChatQRCodeDetector.init(WeChatQRCodeDetector.java:45)
                                                                	at com.king.wechat.qrcode.app.MainActivity.onCreate(MainActivity.kt:47)
                                                                	at android.app.Activity.performCreate(Activity.java:8129)
                                                                	at android.app.Activity.performCreate(Activity.java:8113)
                                                                	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1359)
                                                                	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3736)
                                                                	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3921)
                                                                	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2328)
                                                                	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                	at android.os.Looper.loop(Looper.java:257)
                                                                	at android.app.ActivityThread.main(ActivityThread.java:8244)
                                                                	at java.lang.reflect.Method.invoke(Native Method)
                                                                	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
                                                                	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)

**Comment by SIAWET** [comment]
发现 只要不使用arm64-v8a 就不会闪退
![3CCE5FDA-0CEB-45ad-A8EC-5922A3777DD4](https://github.com/jenly1314/WeChatQRCode/assets/65796770/d0ffa709-103e-40eb-8762-ad90b72ad41d)

**Comment by SIAWET** [comment]
在红米pad上进行了重试 现象一致 应该不是手机的问题

**Comment by jenly1314** [comment]
> 发现 只要不使用arm64-v8a 就不会闪退 ![3CCE5FDA-0CEB-45ad-A8EC-5922A3777DD4](https://private-user-images.githubusercontent.com/65796770/308892993-d0ffa709-103e-40eb-8762-ad90b72ad41d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNTkxMjMsIm5iZiI6MTcwOTI1ODgyMywicGF0aCI6Ii82NTc5Njc3MC8zMDg4OTI5OTMtZDBmZmE3MDktMTAzZS00MGViLTg3NjItYWQ5MGI3MmFkNDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDAyMDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMmE0ZjMzMjY3OGRjYjI1MmIzYzIwMWM3YTM5NjBjYjFjMmEwNjMzMGYxZTcwMjI1YzEzYzEzOGE4ZTY3N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZazFHUY3-Kx5bYhRU6mBnOBi1AQsKS5iwKGhIKD4yvY)

这个周末我抽空验证下，到时候给你答复。

**Comment by jenly1314** [comment]
> > 发现 只要不使用arm64-v8a 就不会闪退 ![3CCE5FDA-0CEB-45ad-A8EC-5922A3777DD4](https://private-user-images.githubusercontent.com/65796770/308892993-d0ffa709-103e-40eb-8762-ad90b72ad41d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNTkxMjMsIm5iZiI6MTcwOTI1ODgyMywicGF0aCI6Ii82NTc5Njc3MC8zMDg4OTI5OTMtZDBmZmE3MDktMTAzZS00MGViLTg3NjItYWQ5MGI3MmFkNDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDAyMDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMmE0ZjMzMjY3OGRjYjI1MmIzYzIwMWM3YTM5NjBjYjFjMmEwNjMzMGYxZTcwMjI1YzEzYzEzOGE4ZTY3N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZazFHUY3-Kx5bYhRU6mBnOBi1AQsKS5iwKGhIKD4yvY)
> 
> 这个周末我抽空验证下，到时候给你答复。

已验证，测试一切正常。你是不是ndk的 abiFilters 配置支持了 arm64-v8a， 但没有依赖对应的so库：**opencv-armv64** ？
